// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v5.28.2
// source: broker.proto

package proto

import (
	context "context"
	proto "go.unistack.org/micro-broker-grpc/v3/proto"
	client "go.unistack.org/micro/v3/client"
)

var (
	BrokerName = "Broker"
)

type BrokerClient interface {
	Publish(ctx context.Context, req *proto.Message, opts ...client.CallOption) (*proto.Response, error)
	Subscribe(ctx context.Context, req *proto.SubscribeRequest, opts ...client.CallOption) (Broker_SubscribeClient, error)
}

type Broker_SubscribeClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*proto.Message, error)
}

type BrokerServer interface {
	Publish(ctx context.Context, req *proto.Message, rsp *proto.Response) error
	Subscribe(ctx context.Context, req *proto.SubscribeRequest, stream Broker_SubscribeStream) error
}

type Broker_SubscribeStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *proto.Message) error
}
